image: node:4.4.3

before_script:
  - apt-get update -qq && apt-get install -y -qq curl
  - npm install
  - npm install forever browserify uglifyjs -g
  - mkdir -p config
  - cp .gitlab-ci.config.json config/config.json

cache:
  paths:
    - node_modules/
    - config/

build:
  stage: build
  script:
    - npm run prod
    - forever start server.js
    - sleep 5
    - curl -I http://127.0.0.1:3000/prod.js
